// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa7voc-DvrBsFszor-bBzP0PyDxsP5RdU',
    appId: '1:575979819735:web:8e36868067fb36f6a71692',
    messagingSenderId: '575979819735',
    projectId: 'todoapp-87a68',
    authDomain: 'todoapp-87a68.firebaseapp.com',
    storageBucket: 'todoapp-87a68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhKvQNiRi66wCusm857-vjlghzpTj5HI4',
    appId: '1:575979819735:android:98f84dc7a780c781a71692',
    messagingSenderId: '575979819735',
    projectId: 'todoapp-87a68',
    storageBucket: 'todoapp-87a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj3m0AoyEcADTE14J3Lz6UKFTTNgq8G-c',
    appId: '1:575979819735:ios:6399eaf6bd460adfa71692',
    messagingSenderId: '575979819735',
    projectId: 'todoapp-87a68',
    storageBucket: 'todoapp-87a68.appspot.com',
    iosClientId:
        '575979819735-s8ad4cpmpou62ejqbf55u9e7c4ldk2e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj3m0AoyEcADTE14J3Lz6UKFTTNgq8G-c',
    appId: '1:575979819735:ios:6399eaf6bd460adfa71692',
    messagingSenderId: '575979819735',
    projectId: 'todoapp-87a68',
    storageBucket: 'todoapp-87a68.appspot.com',
    iosClientId:
        '575979819735-s8ad4cpmpou62ejqbf55u9e7c4ldk2e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );
}*/
